### ISSUE TITLE
Emails not being received

### ISSUE THREAD

**Issue by d4vidsha** [d4vidsha/scheduler#2]
Invoking a test email (http://localhost.davidsha.me/docs#/utils/utils-test_email) doesn't seem to work.

**Comment by SureshPradhana** [comment]
@d4vidsha I am trying to fix this issue.
The endpoint http://localhost.davidsha.me/docs#/utils/utils-test_email requires an Authorization header in the request. Additionally, the SMTP_HOST, SMTP_PORT, SMTP_TLS, and SMTP_SSL settings are being overridden in the `docker-compose.override.yml` file, causing the email not to be received as the environment variables set in the `.env` file are being ignored.

**Comment by d4vidsha** [comment]
Thanks for looking at this, I've just taken a look too and can see that things are all working as intended through Mailcatcher. If you're running locally, you can see something similar when navigating into http://localhost:1080/ (or http://localhost.davidsha.me:1080/ if you set up your `.env` and `frontend/.env` files to point to that url).

The next step for this issue would be to set up SMTP environment variables for `https://staging-scheduler.davidsha.me` which will have to be something I set up.

![Screenshot 2024-08-04 at 7 56 45 pm](https://github.com/user-attachments/assets/317f1396-d1db-4f75-9c8b-b40b778e656e)

P.S: 
> requires an Authorization header in the request

You can sign in to the backend using swagger docs by hitting the lock symbol.
![Screenshot 2024-08-04 at 8 02 48 pm](https://github.com/user-attachments/assets/16d68b16-9e9f-427c-9bab-fe5df489e89f)

**Comment by SureshPradhana** [comment]
Thanks for the update and for the Swagger sign-in info. I’ll test the email with Mailcatcher. Let me know if you need anything else.

**Comment by d4vidsha** [comment]
I've set up an [smtp2go](https://www.smtp2go.com/) account now following the advice I found from [r/selfhosted Reddit post](https://www.reddit.com/r/selfhosted/comments/14hvn9u/best_free_smtp_service/). Both `staging-scheduler.davidsha.me` and `scheduler.davidsha.me` (when it's deployed in the first release of this app) will now send emails from smtp2go.
