### ISSUE TITLE
Make profile picture hover show that it is clickable

### ISSUE THREAD

**Issue by d4vidsha** [d4vidsha/scheduler#20]
Similar to how GitHub does this.

**Comment by SureshPradhana** [comment]
@d4vidsha, I made the avatar a cursor pointer. Is this what you expected, or did you want a dropdown to show on hover?

**Comment by d4vidsha** [comment]
> Is this what you expected, or did you want a dropdown to show on hover?

What you did was perfect, thanks man 👊
