### ISSUE TITLE
"Sign Up" button does not redirect to the sign-up page

### ISSUE THREAD

**Issue by SureshPradhana** [d4vidsha/scheduler#35]
The `Don't have an account? Sign Up` button from https://staging-scheduler.davidsha.me/login is not redirecting to the sign-up page. Instead, it redirects to the login page

**Comment by d4vidsha** [comment]
Thanks @SureshPradhana, the login page will be coming soon! Hasn't yet been implemented, so for the time being demo@example.com is the only account active until we've implemented sign up.

**Comment by d4vidsha** [comment]
I'm picking this one up as the signup page will be implemented in #37.
